[project]
authors = [{ name = "Christian Stefanescu" }]
name = "untangle"
version = "1.2.1"
description = "Converts XML to Python objects"
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"

dependencies = ["defusedxml==0.7.1"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.8",
    "ty>=0.0.83",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

